from python_pure_datastructures.linked_list import SingleLinkedList
linkedlist = SingleLinkedList()
linkedlist.insert_at_end(1)
linkedlist.insert_at_end(2)
linkedlist.insertAt(3,1)
linkedlist.insertAt(3,4)
linkedlist.print_list()
# linkedlist.delete_from_end()
linkedlist.delete_at(3)
linkedlist.print_list()
# linkedlist.delete_from_beginning()
# linkedlist.print_list()